# This is a basic workflow to help you get started with Actions

name: Firefox UI Tests

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      specs:
        description: 'Run ALL or unique spec'
        default: cypress/integration/*
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  firefox-ui-tests:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node14.19.0-chrome100-ff99-edge
      options: --user 1001
    strategy:
      fail-fast: false
      matrix:
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Ping API(Heroku)
        uses: Leocardoso94/is-my-site-up@v1.2
        with:
          site: https://samuraibs-api-simoes.herokuapp.com
          
      - name: 'UI Tests - Firefox'
        uses: cypress-io/github-action@v4
        with:
          install-command: yarn install
          wait-on: 'https://samuraibs-web-simoes.herokuapp.com'
          wait-on-timeout: 120
          browser: firefox
          record: true
          parallel: true
          group: 'UI - Firefox'
          spec: ${{ github.event.inputs.specs }}
        env:
          TZ: America/Sao_Paulo
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
